### PR TITLE
Add helper script

### PR DESCRIPTION
**Pull request by jcfr**
Add helper script allowing to automatically mount current folder

Instead of running the image using:

```
  $ docker run --rm travis-cli encrypt SECRET=123 -r org/repo
```

The following can be done:

```
  $ /path/to/travis-cli.sh encrypt SECRET=123 -r org/repo
```

### CODE REVIEW

**Comment by jcfr** [comment]
@caktux To ensure the metadata reported on https://microbadger.com are up-to-date, please consider also adding a webhook to your docker hub.

For details, see https://microbadger.com/images/caktux/travis-cli/

**Comment by jcfr** [comment]
Listed below are folks who may be interested by this updated image and its new convenient script:

@mgruener (https://github.com/mgruener/docker-travis-cli)
@ViBiOh (https://github.com/ViBiOh/docker-travis-cli)
@gesellix (https://github.com/gesellix/travis-ci-tools)
@jgiovaresco (https://github.com/jgiovaresco/dockerfiles/tree/master/travis-cli)
@jamespamplin (https://github.com/jamespamplin/docker-alpine-travis-cli)
@smartcanvas (https://github.com/smartcanvas/docker-ruby-travis-cli)
@Bilge (https://github.com/Bilge/Travis-CLI)
@tracker1 (https://github.com/tracker1/dockerfiles/tree/master/travis-ci-cli)
@kkohtaka (https://github.com/kkohtaka/docker-traviscli)
@andredumas (https://github.com/andredumas/docker-travis-ci-cli)
@antonmry (https://github.com/antonmry/travis-docker)

And while looking at existing "travis-cli" projects in docker hub, I discovered https://github.com/drunner/drunner used within https://github.com/drunner/travislint (@drunner), I wonder if it would make things easier ...

**Comment by Bilge** [comment]
Don't ever do that again.

**Comment by ViBiOh** [comment]
Hi @jcfr,

Thanks you for mentionning your work with Travis CLI.

I personnally use my bashrc configuration https://github.com/ViBiOh/dotfiles/blob/master/.app_dock#L12 to have a travis cli from bash (without "script" to launch). I'm working of environment variable or specific entrypoint (just need time) in order to catch github-token or login/psw for automatic login before executing a task.

Think something like

```
travis --github-token MyAwesomeToken encrypt myFile
```

-> Two actions :

```
travis --github-token MyAwesomeToken
travis encrypt myFile
```

My container's user is root (it's bad I know) but I have no rights to consider. Some others of my containers use a different user (e.g. npm, mvn) and I use an alias to change rights permissions https://github.com/ViBiOh/dotfiles/blob/master/.dockerrc#L23

**Comment by jcfr** [comment]
@ViBiOh Neat collection of dotfiles.

Look like this particular PR will not really improve your workflow.

> My container's user is root

Regarding user management, the helper script `travis-cli.sh` will get the current UID and GID, and run the client using this user. See https://github.com/jcfr/docker-travis-cli/blob/e08199f54ddb436931cffd8b80026575a3455b30/imagefiles/entrypoint.sh#L6-L30

@caktux Let me know if there is anything I could improve to  get the PR integrated. It will be neat to maintain and contribute to one repo. Let me know what you think.

**Pull request closed without merging**
